package pacoteCalculadora;

public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbl_ChooseNumber = new javax.swing.JLabel();
        spn_NumberPicker = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        btn_CalcularValores = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_RestoDivisao = new javax.swing.JLabel();
        lbl_ElevadoCubo = new javax.swing.JLabel();
        lbl_RaizQuadrada = new javax.swing.JLabel();
        lbl_RaizCubica = new javax.swing.JLabel();
        lbl_ValorAbsoluto = new javax.swing.JLabel();
        lbl_Result_RestoDivisao = new javax.swing.JLabel();
        lbl_Result_ElevadoCubo = new javax.swing.JLabel();
        lbl_Result_RaizQuadrada = new javax.swing.JLabel();
        lbl_Result_RaizCubica = new javax.swing.JLabel();
        lbl_Result_ValorAbsoluto = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Calculadora");
        setLocation(new java.awt.Point(600, 250));
        setResizable(false);

        lbl_ChooseNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_ChooseNumber.setForeground(new java.awt.Color(0, 0, 255));
        lbl_ChooseNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ChooseNumber.setText("Escolha um número");

        spn_NumberPicker.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        btn_CalcularValores.setText("Calcular");
        btn_CalcularValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularValoresActionPerformed(evt);
            }
        });

        lbl_RestoDivisao.setText("Resto da divisão por 2: ");

        lbl_ElevadoCubo.setText("Elevado ao Cubo: ");

        lbl_RaizQuadrada.setText("Raiz Quadrada: ");

        lbl_RaizCubica.setText("Raiz Cúbica: ");

        lbl_ValorAbsoluto.setText("Valor Absoluto:");

        lbl_Result_RestoDivisao.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Result_RestoDivisao.setText("0");

        lbl_Result_ElevadoCubo.setForeground(new java.awt.Color(255, 0, 102));
        lbl_Result_ElevadoCubo.setText("0");

        lbl_Result_RaizQuadrada.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Result_RaizQuadrada.setText("0");

        lbl_Result_RaizCubica.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Result_RaizCubica.setText("0");

        lbl_Result_ValorAbsoluto.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Result_ValorAbsoluto.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(lbl_ChooseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(spn_NumberPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(btn_CalcularValores, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_RestoDivisao)
                                        .addComponent(lbl_ElevadoCubo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_RaizCubica, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_ValorAbsoluto, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lbl_RaizQuadrada))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Result_ValorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_Result_RestoDivisao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(lbl_Result_RaizCubica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_Result_RaizQuadrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_Result_ElevadoCubo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 281, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbl_ChooseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spn_NumberPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CalcularValores, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_RestoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Result_RestoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ElevadoCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Result_ElevadoCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_RaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Result_RaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_RaizCubica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Result_RaizCubica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ValorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Result_ValorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CalcularValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularValoresActionPerformed
        
        //Obtendo o Número
        int numeroEscolhido = Integer.parseInt(spn_NumberPicker.getValue().toString());
         
        //Cálculo do Resto da Divisão por 2
        int var_lbl_Result_RestoDivisao = (numeroEscolhido % 2);

        //Cálculo da Elevação ao Cubo
        var var_lbl_Result_ElevadoCubo = (float) Math.pow(numeroEscolhido,3.0);
        
        //Cálculo da Raiz Quadrada
        double var_lbl_Result_RaizQuadrada = (Math.sqrt(numeroEscolhido)); 
        
        //Cálculo Raiz Cúbica
        float var_lbl_Result_RaizCubica = (float)(Math.cbrt(numeroEscolhido));
        
        //Cálculo Valor Absoluto    
        var var_lbl_Result_ValorAbsoluto = (Math.abs(numeroEscolhido));
        
        //Resultados para exibição no Label_Resultado       
        lbl_Result_RestoDivisao.setText(Float.toString(var_lbl_Result_RestoDivisao));      
        
        lbl_Result_ElevadoCubo.setText(Double.toString(var_lbl_Result_ElevadoCubo));
                     
        //lbl_Result_RaizQuadrada.setText(Double.toString(var_lbl_Result_RaizQuadrada));
        lbl_Result_RaizQuadrada.setText(String.format("%.2f",var_lbl_Result_RaizQuadrada));
        
        //lbl_Result_RaizCubica.setText(Double.toString(var_lbl_Result_RaizCubica));
        lbl_Result_RaizCubica.setText(String.format("%.2f",var_lbl_Result_RaizCubica));
        
        lbl_Result_ValorAbsoluto.setText(Integer.toString(var_lbl_Result_ValorAbsoluto));
        
              
    }//GEN-LAST:event_btn_CalcularValoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CalcularValores;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_ChooseNumber;
    private javax.swing.JLabel lbl_ElevadoCubo;
    private javax.swing.JLabel lbl_RaizCubica;
    private javax.swing.JLabel lbl_RaizQuadrada;
    private javax.swing.JLabel lbl_RestoDivisao;
    private javax.swing.JLabel lbl_Result_ElevadoCubo;
    private javax.swing.JLabel lbl_Result_RaizCubica;
    private javax.swing.JLabel lbl_Result_RaizQuadrada;
    private javax.swing.JLabel lbl_Result_RestoDivisao;
    private javax.swing.JLabel lbl_Result_ValorAbsoluto;
    private javax.swing.JLabel lbl_ValorAbsoluto;
    private javax.swing.JSpinner spn_NumberPicker;
    // End of variables declaration//GEN-END:variables
}
