package tela_Triangulo;

import javax.swing.JOptionPane;

public class Tela_JFrame extends javax.swing.JFrame {

    public Tela_JFrame() {
        initComponents();
        result_Panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Titulo = new javax.swing.JLabel();
        lbl_A = new javax.swing.JLabel();
        lbl_B = new javax.swing.JLabel();
        lbl_C1 = new javax.swing.JLabel();
        slider_A = new javax.swing.JSlider();
        slider_B = new javax.swing.JSlider();
        slider_C = new javax.swing.JSlider();
        lbl_slider_A_Value = new javax.swing.JLabel();
        lbl_slider_B_Value = new javax.swing.JLabel();
        lbl_slider_C_Value = new javax.swing.JLabel();
        btn_Calular = new javax.swing.JButton();
        foto_Triang = new javax.swing.JLabel();
        result_Panel = new javax.swing.JPanel();
        result_Panel_lbl_Forma = new javax.swing.JLabel();
        result_Panel_lbl_Tipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo de Triângulo");
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);

        lbl_Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_Titulo.setText("<html>Determinar Tipo de Triâgulo</html>");
        lbl_Titulo.setToolTipText("");

        lbl_A.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_A.setText("LADO A");

        lbl_B.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_B.setText("LADO B");

        lbl_C1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_C1.setText("LADO C");

        slider_A.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_AStateChanged(evt);
            }
        });
        slider_A.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                slider_AMouseWheelMoved(evt);
            }
        });

        slider_B.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_BStateChanged(evt);
            }
        });
        slider_B.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                slider_BMouseWheelMoved(evt);
            }
        });

        slider_C.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_CStateChanged(evt);
            }
        });

        lbl_slider_A_Value.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_slider_A_Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_slider_A_Value.setText("50");

        lbl_slider_B_Value.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_slider_B_Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_slider_B_Value.setText("50");

        lbl_slider_C_Value.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_slider_C_Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_slider_C_Value.setText("50");

        btn_Calular.setText("Calcular");
        btn_Calular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalularActionPerformed(evt);
            }
        });

        foto_Triang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/image-removebg-preview.png"))); // NOI18N

        result_Panel_lbl_Forma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        result_Panel_lbl_Forma.setForeground(new java.awt.Color(51, 0, 204));
        result_Panel_lbl_Forma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result_Panel_lbl_Forma.setText("<html>Forma ou Não</html>");

        result_Panel_lbl_Tipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        result_Panel_lbl_Tipo.setForeground(new java.awt.Color(51, 0, 204));
        result_Panel_lbl_Tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result_Panel_lbl_Tipo.setText("<html>Tipo</html>");

        javax.swing.GroupLayout result_PanelLayout = new javax.swing.GroupLayout(result_Panel);
        result_Panel.setLayout(result_PanelLayout);
        result_PanelLayout.setHorizontalGroup(
            result_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_PanelLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(result_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result_PanelLayout.createSequentialGroup()
                        .addComponent(result_Panel_lbl_Forma, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result_PanelLayout.createSequentialGroup()
                        .addComponent(result_Panel_lbl_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        result_PanelLayout.setVerticalGroup(
            result_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_Panel_lbl_Forma, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_Panel_lbl_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(lbl_A, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbl_B, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_C1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(slider_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(slider_B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(slider_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_slider_A_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_slider_B_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_slider_C_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(foto_Triang))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btn_Calular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(result_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_A, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_B, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(slider_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_slider_A_Value, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(slider_B, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_slider_B_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(slider_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_slider_C_Value, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(lbl_C1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(foto_Triang, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Calular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(result_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slider_AStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_AStateChanged
        lbl_slider_A_Value.setText(Integer.toString(slider_A.getValue()));
    }//GEN-LAST:event_slider_AStateChanged

    private void slider_BStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_BStateChanged
        lbl_slider_B_Value.setText(Integer.toString(slider_B.getValue()));
    }//GEN-LAST:event_slider_BStateChanged

    private void slider_CStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_CStateChanged
        lbl_slider_C_Value.setText(Integer.toString(slider_C.getValue()));
    }//GEN-LAST:event_slider_CStateChanged

    private void btn_CalularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalularActionPerformed

        //Deixar painel visível, ao clicar em Calcular
        

        //Atribuindo o valor dos Sliders nas variáveis
        int a = slider_A.getValue();
        int b = slider_B.getValue();
        int c = slider_C.getValue();

        if (a < b + c && b < a + c && c < a + b) {
            result_Panel.setVisible(true);
            result_Panel_lbl_Tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            result_Panel_lbl_Forma.setFont(new java.awt.Font("Segoe UI", 0, 24));
            result_Panel_lbl_Forma.setText("Forma um triângulo");
            if (a == b && b == c) {
                result_Panel_lbl_Tipo.setText("Equilátero");
            } else if (a != b && b != c && a != c) {
                result_Panel_lbl_Tipo.setText("Escaleno");
            } else {
                result_Panel_lbl_Tipo.setText("Isóceles");
            }

        } else {
            result_Panel.setVisible(false);
            JOptionPane.showMessageDialog(null,"Não forma um triângulo ","Erro",JOptionPane.ERROR_MESSAGE);
            
            /*
            result_Panel_lbl_Tipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            result_Panel_lbl_Forma.setFont(new java.awt.Font("Segoe UI", 0, 18));
            result_Panel_lbl_Forma.setText("<html>Não é possível construir um triângulo com essas medidas,<br> pois não existe ponto de encontro nas trajetórias dos segmentos</br></html>");
            result_Panel_lbl_Tipo.setText("---");
            */
        }


    }//GEN-LAST:event_btn_CalularActionPerformed

    private void slider_AMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_slider_AMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_slider_AMouseWheelMoved

    private void slider_BMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_slider_BMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_slider_BMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calular;
    private javax.swing.JLabel foto_Triang;
    private javax.swing.JLabel lbl_A;
    private javax.swing.JLabel lbl_B;
    private javax.swing.JLabel lbl_C1;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_slider_A_Value;
    private javax.swing.JLabel lbl_slider_B_Value;
    private javax.swing.JLabel lbl_slider_C_Value;
    private javax.swing.JPanel result_Panel;
    private javax.swing.JLabel result_Panel_lbl_Forma;
    private javax.swing.JLabel result_Panel_lbl_Tipo;
    private javax.swing.JSlider slider_A;
    private javax.swing.JSlider slider_B;
    private javax.swing.JSlider slider_C;
    // End of variables declaration//GEN-END:variables
}
